### ISSUE TITLE
Sponsor page overhaul

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#111]
We should eventually move our sponsors/supporters to their own page and back their logos with more thoughtful wording. Doing something along the lines of what CODE2040 has would be nice (see http://www.code2040.org/).

**Comment by jonleung** [comment]
@zachlatta I think it is fine as it is now. Thoughts on just closing this issue for now until it becomes more of a problem?

**Comment by MaxWofford** [comment]
I second this^

**Comment by jonleung** [comment]
Closing this for now to bias for closing issues. Feel free to reopen @zachlatta.
