### ISSUE TITLE
Put call to action above the fold and at bottom of website

### ISSUE THREAD

**Issue by jonleung** [hackclub/website#119]
Look at make schools site:
- they have apply now above the fold
- and at the bottom of the page

For us, like PennApps's website, there are 2 calls to action.
- apply now
- follow up more

We should have both of these call to actions above the fold right next to each other (like the above aforementioned website).

And at the very bottom of the page.

**Comment by MaxWofford** [comment]
Our metrics from hack-camp's website say that 0% of users went to the bottom application link. Maybe just having this at the top of the page will have the same effect?

**Comment by zachlatta** [comment]
Agreed with just having it at the top of the page.

**Comment by jonleung** [comment]
Closing because implementing this feature is not useful.

It would be cool data like this could inform more decisions we make.
