### ISSUE TITLE
Move mailing list signup to the top of the page

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#141]
In the Hack Camp website, I believe about 0% of the signups came from people clicking the "Apply Now" button on the bottom of the page (@MaxWofford can confirm/deny this). See below for reference:

![screencapture-camp-hackedu-us-1439228867209](https://cloud.githubusercontent.com/assets/992248/9178734/4a867b22-3f4d-11e5-8a7d-e104d046805e.png)

What if we moved the mailing list signup box to the top of the page, next to or below the top heading?

**Comment by jonleung** [comment]
Closing this because Hack Camp is over.

**Comment by jonleung** [comment]
Oops, I realized I accidently closed the issue without properly understanding it: this is a change to the `Hack Club` website, not `hack camp`. Re-opening the issue. I think this is a good idea!
