### ISSUE TITLE
Add Mixpanel analytics

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/website#153]

**Comment by jonleung** [comment]
@zachlatta @MaxWofford, do we still want to do this?

**Comment by MaxWofford** [comment]
It's probably worth our time to have some form of analytics. It might be worth our time to just set up serverside analytics (because everyone uses ad-blockers)

**Comment by jonleung** [comment]
^ makes sense to me

**Comment by MaxWofford** [comment]
@zachlatta What are your thoughts on piwik analytics?

**Comment by zachlatta** [comment]
Let's hold off on Mixpanel for now and just continue to use Google Analytics. Once we start focusing on optimizing our website's onboarding, we can incorporate a more in-depth analytics product.
