### ISSUE TITLE
Unable to find name of high schools

### ISSUE THREAD

**Issue by ZucchiniZe** [hackclub/website#169]
You can't find out the names of the current high schools unless you zoom in really far to see what is labeled on google maps.

**Comment by jonleung** [comment]
Thanks for the feedback @ZucchiniZe!

**Comment by jonleung** [comment]
@MaxWofford @zachlatta is there a way to fix this?

**Comment by MaxWofford** [comment]
@jonleung Yep! I'd be happy to look into this after I get back.

**Comment by zachlatta** [comment]
I believe Google Maps has a popup of sorts that we can use to display the
names of schools.

On Sun, Sep 20, 2015 at 3:48 AM, Max Wofford <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> Yep! I'd be happy to look into
> this after I get back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/169#issuecomment-141774968>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Whoops, accidentally assigned myself.

**Comment by MaxWofford** [comment]
Closing this for now, but if anyone wants to take this, feel free. 

/cc @ZucchiniZe
