### ISSUE TITLE
Update Website stats & maps

### ISSUE THREAD

**Issue by saescapa** [hackclub/website#173]
The google maps and the statistics do not match. There are 46 (44 in the US) schools on the map while on the statistics there are 40.

**Comment by MaxWofford** [comment]
thanks for catching this!

here's the random fact of the day:
![](http://quickme.me/showerthoughts.gif)

**Comment by jonleung** [comment]
@zachlatta @MaxWofford, has this been fixed yet? Is there a way that we can make sure that adding more clubs is easily reflected on the map / stats?

**Comment by zachlatta** [comment]
Most recent stats (I've updated all the clubs shown on the maps, the first section with stats needs to be updated though):

- 69 clubs
- 16 states
- 7 countries
- 1,500+ students reached

Rest of the stats are the same.
