### ISSUE TITLE
Add Metmets's school to the map on the website.

### ISSUE THREAD

**Issue by metmets** [hackclub/website#178]
As I have noticed metmets's school hasn't been added to the google map(s) on the main website (https://hackclub.io/).

**Comment by zachlatta** [comment]
Oh snap! We'll fix that right away. I'm on it now.

**Comment by zachlatta** [comment]
Added!
![tmp](https://cloud.githubusercontent.com/assets/992248/11754500/a225ffec-a000-11e5-8da6-35312cdc7b55.png)

**Comment by zachlatta** [comment]
Thanks again @metmets :heart:.

**Comment by jonleung** [comment]
Woo!
