### ISSUE TITLE
Update the name at the donation website/update PayPal name.

### ISSUE THREAD

**Issue by metmets** [hackclub/website#179]
As I have noticed, the page where you can donate to Hack Club, it still says hackEDU.

**Comment by jonleung** [comment]
<3

/cc @zachlatta @MaxWofford

**Comment by zachlatta** [comment]
So sorry for taking so long to get to this. On it now!

**Comment by zachlatta** [comment]
Fixed! Going to https://donate.hackclub.io should now have "Hack Club" instead of "hackEDU".

**Comment by zachlatta** [comment]
Thanks so much for reporting this @metmets :heart:
