### ISSUE TITLE
Improve site load times

### ISSUE THREAD

**Issue by ZucchiniZe** [hackclub/website#180]
The site takes on average 2.5s to load up and around 1 second until first paint. Lets see if we can improve this :smiley:!

**Comment by zachlatta** [comment]
I'm so sorry for not getting back to this earlier. Totally agree that major performance improvements can be made.

@ZucchiniZe: would you be interested in taking point on this?

**Comment by ZucchiniZe** [comment]
Well, Maybe the first point of action would be to switch from a dynamic site (rails) to something static and just connect through an api for things that require a backend.

**Comment by zachlatta** [comment]
That's a pretty drastic change and I'm not sure how much it'd actually speed things up.

If I had to guess, there are probably either large assets being loaded that don't need to be. When I get home in 30, I'll check out the network tab in Chrome.

**Comment by ZucchiniZe** [comment]
It doesn't look like there are that many large assets being loaded other than the map, but the JS and CSS files take a while to load, so I would maybe think about using some sort of CDN for them.
