### ISSUE TITLE
Clarify that Hack Clubs require no previous coding experience

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#191]
I was talking with a beginner, I forget whom, and they mentioned that Hack Clubs seemed intimidating because it sounded like you had to already know how to code.

We should change this!

**Comment by MaxWofford** [comment]
@zachlatta Was this a club leader applicant, or a member?

**Comment by MaxWofford** [comment]
Closed by https://github.com/hackclub/website/pull/197

**Comment by zachlatta** [comment]
I forget exactly, but it was an existing club leader or member – was either
at a hackathon or in a Google Hangout.

On Tue, Feb 16, 2016 at 3:55 PM, Max Wofford <notifications@github.com>
wrote:

> Closed by #197 <https://github.com/hackclub/website/pull/197>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/191#issuecomment-184930151>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
