### ISSUE TITLE
Don't cluster clubs in map

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#194]
Currently the clubs shown on our map are clustered, as such:

![tmp](https://cloud.githubusercontent.com/assets/992248/13084750/9015f8f2-d48f-11e5-937d-05f70fcac75f.png)

I propose changing this to remove the clusters. I think it looks a bit nicer and makes our reach seem broader.

**Comment by MaxWofford** [comment]
:+1:

**Comment by jkwok91** [comment]
I need some assistance with this:
https://github.com/hackclub/website/blob/e91b464c1e9b5160bd45d751fcbefd94f09ea99b/app/controllers/pages_controller.rb#L16
https://github.com/apneadiving/Google-Maps-for-Rails/wiki/Markers#options

**Comment by zachlatta** [comment]
@MaxWofford: do you think you could help out?

On Thu, Mar 10, 2016 at 3:47 PM, JESSICA <notifications@github.com> wrote:

> I need some assistance with this:
>
> https://github.com/hackclub/website/blob/e91b464c1e9b5160bd45d751fcbefd94f09ea99b/app/controllers/pages_controller.rb#L16
> https://github.com/apneadiving/Google-Maps-for-Rails/wiki/Markers#options
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/194#issuecomment-195105054>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Going to go ahead and close this due to lack of progress.

**Comment by zachlatta** [comment]
(also because of the @LabLayers redesign)
