### ISSUE TITLE
Improve Google search result image

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#195]
When you Google "Hack Club", you get our website next to a bunch of noise:

![tmp](https://cloud.githubusercontent.com/assets/992248/13084774/c346f74e-d48f-11e5-9cd2-5014ec67c38d.png)

Obviously we don't have the web presence that Slack has, but do compare to what you get when googling "Slack":

![tmp](https://cloud.githubusercontent.com/assets/992248/13084795/e8653838-d48f-11e5-963a-ecd49c904043.png)

I propose making a couple changes to the meta info that Googlebot sees when it goes to our website:

- Improve the description of Hack Club under the website link. Something closer in length and clarity to what Slack has ("Slack brings all your communication together in one place. It's real-time messaging, archiving and search for modern teams.")
- Just like how Slack has a bunch of sublinks to their site under the primary link, we should figure out how to get the same for Hack Club (and each link should have an appropriate description)

**Comment by jkwok91** [comment]
TODO
https://developers.google.com/structured-data/schema-org
