### ISSUE TITLE
Change "year" selector on application to not use US-specific terms

### ISSUE THREAD

**Issue by remixz** [hackclub/website#201]
![screen shot 2016-02-25 at 1 30 06 pm](https://cloud.githubusercontent.com/assets/1459603/13335075/f84fb580-dbc3-11e5-82ae-9868ad650870.png)

At least in Canada, we generally don't use these terms to describe what grade we're in. I think it might be better just to have a more general grade selection, maybe something like:

> **Year/Grade:**
* 8 or earlier
* 9
* 10
* 11
* 12

I include 8 or earlier because we're starting to get some interest from middle schools. Even if we're targeting high schools, we might as well capture these younger students early on in the process, so we can help guide them to other resources, if we feel they aren't a good fit for starting a club yet.

**Comment by zachlatta** [comment]
Agreed, and while we're at it, we may as well add options for teachers (and maybe parents).
