### ISSUE TITLE
Update team page

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/website#202]
Let's get @remixz on the team page!

**Comment by zachlatta** [comment]
I actually have a local branch for this. Let me turn it into a pull request
:-).

On Mon, Feb 29, 2016 at 7:35 PM, Max Wofford <notifications@github.com>
wrote:

> Let's get @remixz <https://github.com/remixz> on the team page!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/202>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com
