### ISSUE TITLE
Update website press

### ISSUE THREAD

**Issue by jkwok91** [hackclub/website#209]
Not 100% sure if this is necessary (might just be noise for homepage), but Hack Club has had much more coverage in the press since the three things currently on the site!
Discuss.

**Comment by zachlatta** [comment]
Yeah, totally agree. Let's update this.

Things to add off the top of my head:

- Daily Dot
- Forbes
- Business Insider

**Comment by zachlatta** [comment]
Now we should also add CBS Sunday Morning.
