### ISSUE TITLE
Teams page displays weird on Safari Tech Preview

### ISSUE THREAD

**Issue by raysarebest** [hackclub/website#218]
On the Safari Tech Preview on my 15 inch Late-2015 MacBook Pro running the latest OS X 10.11.4, Zach Latta's description renders under the other Zach's, in the same column, leaving a blank space where it looks like Zach Latta's should be
![Screenshot](http://s14.postimg.org/j9omoxua9/Screen_Shot_2016_04_04_at_8_58_11_PM.png)

**Comment by jkwok91** [comment]
I'm getting this view as well on Chrome on 11" Mid 2013 MBA OSX 10.10.5

**Comment by MaxWofford** [comment]
Same on Chrome on xps 13 13" Ubuntu 15

**Comment by zachlatta** [comment]
Oh snap. Fixing right now.

On Mon, Apr 4, 2016 at 7:20 PM, Max Wofford <notifications@github.com>
wrote:

> Same on Chrome on xps 13 13" Ubuntu 15
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/218#issuecomment-205601224>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Closed by #219.
