### ISSUE TITLE
Add Jessica to team page

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/website#222]
@jkwok91

**Comment by zachlatta** [comment]
:+1:

@jkwok91: can you comment with a profile and bio to this issue?

On Tue, Apr 5, 2016 at 5:15 PM, Max Wofford <notifications@github.com>
wrote:

> @jkwok91 <https://github.com/jkwok91>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/222>
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Closed by #232.
