### ISSUE TITLE
Add .TECH logo to website

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#224]
We've partnered with .TECH to offer free domains to everyone that's a part of Hack Club. Formal announcement will be made soon about this.

![tech-logo-with-tagline-600px](https://cloud.githubusercontent.com/assets/992248/14519023/02bc9582-01d1-11e6-94f9-32aaee9b4adc.png)

**Comment by MaxWofford** [comment]
This was closed by #227

**Comment by zachlatta** [comment]
Ah, good catch. Thanks!

On Sun, Apr 17, 2016 at 10:50 AM, Max Wofford <notifications@github.com>
wrote:

> Closed #224 <https://github.com/hackclub/website/issues/224>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/224#event-630439770>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
