### ISSUE TITLE
Map is broken

### ISSUE THREAD

**Issue by zachlatta** [hackclub/website#233]
Map is currently totally broken on the site. There's just a white space where it should be.

Will comment with screenshots in a few minutes.

**Comment by zachlatta** [comment]
![tmp](https://cloud.githubusercontent.com/assets/992248/15201285/4282a4ca-17a4-11e6-978a-c094b8950547.png)

![tmp](https://cloud.githubusercontent.com/assets/992248/15201294/5567b7ba-17a4-11e6-9674-fc6ac3813d0f.png)

Pretty sure it's that first 404 that's breaking things. Chances are updating the gmaps4rails gem will fix this.

**Comment by MaxWofford** [comment]
As of right now I don't think it the gem is working: https://travis-ci.org/apneadiving/Google-Maps-for-Rails/builds/129553203

**Comment by zachlatta** [comment]
@MaxWofford figured it out and closed it in #235.
