### ISSUE TITLE
Sponsor logos are not centered on mobile 

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/website#239]

**Comment by zachlatta** [comment]
Can you include a screenshot? They're looking centered for me.

**Comment by MaxWofford** [comment]
@zachlatta http://peek.usertesting.com/result/14941866645557?autoplay=true

**Comment by zachlatta** [comment]
Cool, thanks.

On Sat, May 21, 2016 at 5:51 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>
> http://peek.usertesting.com/result/14941866645557?autoplay=true
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/website/issues/239#issuecomment-220808245>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Going to go ahead and close this since @lablayers is redesigning our homepage, which won't have sponsor logos on it.
