### ISSUE TITLE
Fix convox login issues with CircleCI tests

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/website#244]
![screenshot_2016-06-12_19 05 03](https://cloud.githubusercontent.com/assets/5891442/15995460/9a3e7514-30d0-11e6-9b3b-5d981c7d100b.png)

**Comment by zachlatta** [comment]
Yeah, good catch. Will fix.

On Sun, Jun 12, 2016 at 7:05 PM, Max Wofford <notifications@github.com>
wrote:

> Assigned #244 <https://github.com/hackclub/website/issues/244> to
> @zachlatta <https://github.com/zachlatta>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/website/issues/244#event-689892315>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA8j-PfvhqUScLBOVNVyteeYRaKK4qb3ks5qLLrfgaJpZM4Iz8e1>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Fixed!

**Comment by zachlatta** [comment]
Deploy is now working.
